-- =====================================================================
-- 0052 Eigene Zeitfenster — der Tag wird selbst geschnitten
--
-- ANLASS (11.08.2026): Fuer die Round-Table-Map galt "LINA kennt nur 6
-- feste Zonen" als Mangel. Das stimmt fuer den Zonenbericht und ist fuer
-- uns trotzdem folgenlos: LINA liefert daneben den STUNDENbericht, und
-- der ist vollstaendig.
--
-- NACHGEMESSEN AM 11.08.2026:
--
--   core.zeitzonenbericht_stunde   10.618.992 Zeilen
--   Stundenraster                  0 bis 23, alle 24 Stunden besetzt
--   Historie                       31.12.2017 bis 07.08.2026, lueckenlos
--   Betriebe                       141 von 141
--
-- Damit ist jedes Zeitfenster frei schneidbar, solange seine Grenzen auf
-- vollen Stunden liegen. Die Summe aller Fenster trifft den Tag exakt,
-- weil sie dieselben Stundenzeilen aufteilt, aus denen LINA auch seine
-- eigenen Zonen bildet (gegengerechnet: Stundensumme gegen Zonensumme,
-- Median-Abweichung 0,00 EUR).
--
-- ---------------------------------------------------------------------
-- WAS NICHT GEHT — die halben Stunden
--
-- LINAs eigene Zonen brechen bei 11:30 und 17:30. Das ist aus
-- Stundenwerten nicht nachbaubar, und der Fehler ist nicht klein:
--
--   Mittagszeit 11:30-14:00 gegen eigenen Schnitt 11-14  ->  +8,4 %
--   Mittagszeit 11:30-14:00 gegen eigenen Schnitt 12-14  ->  -8,4 %
--
-- In Stunde 17 liegen 9,7 % des Tagesumsatzes, in Stunde 11 3,5 %. Wer
-- eine eigene Zone gegen eine LINA-Zone haelt, vergleicht deshalb zwei
-- verschiedene Dinge. DESHALB stehen die eigenen Fenster in einer
-- eigenen Sicht und ueberschreiben core.zeitzonenbericht_zone nicht.
--
-- Praktische Folge: die Fenster der Round-Table-Map muessen auf vollen
-- Stunden definiert werden. Welche Grenzen das sind, ist eine fachliche
-- Festlegung und keine Datenfrage — die Seed-Zeilen unten sind ein
-- Vorschlag, kein Befund.
--
-- ---------------------------------------------------------------------
-- DIE TAGESGRENZE
--
-- Der Geschaeftstag laeuft 08:00 bis 07:59. Die Stunden 0 bis 7 gehoeren
-- zum VORTAG und sind in geschaeftstag bereits umgerechnet (siehe
-- docs/datenherkunft.md). Ein Fenster wie Late Night 22-01 laeuft
-- deshalb ueber Mitternacht und wird ueber stunde >= 22 OR stunde < 1
-- geschnitten, nicht ueber BETWEEN. Genau dafuer gibt es die Spalte
-- ueber_mitternacht: wer sie vergisst, verliert 0,5 % des Umsatzes und
-- merkt es nicht.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Die Fensterdefinition — Stammdaten, keine Konstante im Code
--
-- Als Tabelle und nicht als CASE-Ausdruck in einer Sicht: die Grenzen
-- sind eine fachliche Festlegung, die sich aendern wird. Eine Zeile
-- aendern ist eine Pflege, eine Sicht aendern ist eine Migration.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS manual.zeitfenster (
  fenster_key   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text    NOT NULL UNIQUE,
  stunde_von    smallint NOT NULL CHECK (stunde_von BETWEEN 0 AND 23),
  stunde_bis    smallint NOT NULL CHECK (stunde_bis BETWEEN 0 AND 24),
  reihenfolge   smallint NOT NULL,
  aktiv         boolean  NOT NULL DEFAULT true,
  notiz         text,
  gepflegt_am   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE manual.zeitfenster IS
'Eigene Auswertungsfenster ueber den Geschaeftstag. stunde_von einschliesslich, stunde_bis '
'ausschliesslich — 11 bis 14 sind die Stunden 11, 12, 13. Laeuft stunde_bis <= stunde_von, '
'geht das Fenster ueber Mitternacht (22 bis 1 = Stunden 22, 23, 0). '
'DIE GRENZEN SIND EIN VORSCHLAG. Sie stammen aus LINAs sechs Zonen, auf volle Stunden '
'gerundet und um Early Dinner und Aktionszeit erweitert; die Round-Table-Map nennt sieben '
'Fenster, deren genaue Grenzen der Fachbereich festlegt.';

COMMENT ON COLUMN manual.zeitfenster.stunde_bis IS
'Ausschliesslich. 24 ist erlaubt und meint "bis Tagesende"; fuer Fenster ueber Mitternacht '
'stattdessen einen Wert <= stunde_von setzen.';


-- ---------------------------------------------------------------------
-- Vorschlag: sieben Fenster auf vollen Stunden
--
-- Abgeleitet aus LINAs sechs Zonen, mit zwei Aenderungen: die
-- Happy-Hour-Zone (17:30-19:00) wird zu Early Dinner (17-19), und
-- zwischen Abendessen und Late Night steht die Aktionszeit (21-22) als
-- eigenes Fenster — die Round-Table-Map fuehrt beide getrennt, LINA
-- nicht.
-- ---------------------------------------------------------------------
INSERT INTO manual.zeitfenster (name, stunde_von, stunde_bis, reihenfolge, notiz) VALUES
  ('Fruehstueck',  8, 11, 1, 'LINA: 08:00-11:30, hier auf volle Stunden gerundet'),
  ('Mittagszeit', 11, 14, 2, 'LINA: 11:30-14:00 — eigener Schnitt liegt 8,4 % darueber'),
  ('Nachmittag',  14, 17, 3, 'LINA: 14:00-17:30'),
  ('Early Dinner',17, 19, 4, 'LINA nennt es Happy Hour (17:30-19:00); die Map trennt es von der Aktionszeit'),
  ('Abendessen',  19, 21, 5, 'LINA: 19:00-22:00, hier vor der Aktionszeit gekappt'),
  ('Aktionszeit', 21, 22, 6, 'Eigenes Fenster; LINA fuehrt es nicht getrennt'),
  ('Late Night',  22,  1, 7, 'Laeuft ueber Mitternacht: Stunden 22, 23, 0')
ON CONFLICT (name) DO NOTHING;


-- ---------------------------------------------------------------------
-- Umsatz je Betrieb, Tag und eigenem Fenster
--
-- Der Join ist bewusst ein Bereichsvergleich und kein vorberechnetes
-- Stunden-Fenster-Mapping: aendert jemand eine Fenstergrenze, gilt sie
-- sofort und rueckwirkend fuer die ganze Historie.
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.umsatz_zeitfenster AS
SELECT s.betrieb_key,
       b.name         AS betrieb,
       s.geschaeftstag,
       f.fenster_key,
       f.name         AS fenster,
       f.reihenfolge,
       (f.stunde_bis <= f.stunde_von) AS ueber_mitternacht,
       sum(s.umsatz_netto) AS umsatz_netto
  FROM core.zeitzonenbericht_stunde s
  JOIN core.betrieb b ON b.betrieb_key = s.betrieb_key
  JOIN manual.zeitfenster f
    ON f.aktiv
   AND CASE WHEN f.stunde_bis > f.stunde_von
            THEN s.stunde >= f.stunde_von AND s.stunde < f.stunde_bis
            ELSE s.stunde >= f.stunde_von OR  s.stunde < f.stunde_bis
       END
 GROUP BY s.betrieb_key, b.name, s.geschaeftstag, f.fenster_key, f.name, f.reihenfolge,
          (f.stunde_bis <= f.stunde_von);

COMMENT ON VIEW mart.umsatz_zeitfenster IS
'Umsatz je Betrieb, Geschaeftstag und selbst geschnittenem Zeitfenster, aus dem Stundenbericht. '
'Deckt die volle Historie ab 01.01.2018 ab. NICHT vergleichbar mit core.zeitzonenbericht_zone: '
'LINAs Zonen brechen bei 11:30 und 17:30, diese hier auf vollen Stunden. '
'Wie bei den LINA-Zonen liefert der Stundenbericht nur UMSATZ — keine Gaeste, keine Bons, '
'keine Sparten. Das bleibt offen.';


-- ---------------------------------------------------------------------
-- Probe: decken die Fenster den Tag lueckenlos und ueberschneidungsfrei
--
-- Eine Fensterdefinition mit Loch oder Ueberlappung faellt sonst nicht
-- auf — die Summe ist dann einfach falsch, und zwar plausibel falsch.
-- Erwartung: leer.
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.zeitfenster_pruefung AS
WITH je_stunde AS (
  SELECT g.stunde, count(*) AS fenster
    FROM generate_series(0, 23) AS g(stunde)
    LEFT JOIN manual.zeitfenster f
      ON f.aktiv
     AND CASE WHEN f.stunde_bis > f.stunde_von
              THEN g.stunde >= f.stunde_von AND g.stunde < f.stunde_bis
              ELSE g.stunde >= f.stunde_von OR  g.stunde < f.stunde_bis
         END
   GROUP BY g.stunde
)
SELECT s.stunde,
       s.fenster,
       CASE WHEN s.fenster = 0 THEN 'Stunde faellt aus allen Fenstern'
            ELSE 'Stunde liegt in ' || s.fenster || ' Fenstern gleichzeitig' END AS befund,
       round(u.umsatz) AS umsatz_2026
  FROM je_stunde s
  LEFT JOIN LATERAL (SELECT sum(umsatz_netto) AS umsatz
                       FROM core.zeitzonenbericht_stunde z
                      WHERE z.stunde = s.stunde
                        AND z.geschaeftstag >= DATE '2026-01-01') u ON true
 WHERE s.fenster <> 1
 ORDER BY s.stunde;

COMMENT ON VIEW mart.zeitfenster_pruefung IS
'Stunden, die in keinem oder in mehr als einem Fenster liegen, mit dem Umsatz, der daran '
'haengt. Erwartung: die Stunden 1 bis 7 fallen bewusst heraus (dort liegen 0,2 % des '
'Umsatzes, die Haeuser sind zu). Jede andere Zeile ist ein Definitionsfehler.';


-- ---------------------------------------------------------------------
-- Arbeitsliste Kalender scharf stellen
--
-- 0051 zaehlte jeden Betrieb, der jemals Umsatz gemacht hat — das sind
-- 26, und 17 davon sind seit Jahren zu. Fuer eine Arbeitsliste ist das
-- unbrauchbar: sie soll nennen, wem HEUTE der Kalender fehlt.
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.kalender_fehlend AS
SELECT b.betrieb_key,
       b.name AS betrieb,
       CASE WHEN s.betrieb_key IS NULL THEN 'kein Standort gepflegt'
            ELSE 'PLZ ' || s.plz || ' nicht in manual.plz_bundesland'
       END AS grund,
       u.letzter_umsatztag,
       u.umsatz_2026
  FROM core.betrieb b
  LEFT JOIN manual.betrieb_standort s ON s.betrieb_key = b.betrieb_key
  LEFT JOIN manual.plz_bundesland   p ON p.plz = s.plz
  JOIN LATERAL (SELECT max(geschaeftstag) FILTER (WHERE umsatz_netto > 0) AS letzter_umsatztag,
                       round(sum(umsatz_netto) FILTER (WHERE geschaeftstag >= DATE '2026-01-01')) AS umsatz_2026
                  FROM mart.umsatz_tag t WHERE t.betrieb_key = b.betrieb_key) u ON true
 WHERE p.plz IS NULL
   AND u.umsatz_2026 > 0
 ORDER BY u.umsatz_2026 DESC;

COMMENT ON VIEW mart.kalender_fehlend IS
'Betriebe mit Umsatz im laufenden Jahr, fuer die kein Bundesland ableitbar ist — nach Umsatz '
'sortiert, damit der teuerste Fall oben steht. Am 11.08.2026 sind es 9, angefuehrt vom '
'umsatzstaerksten Haus der Gruppe. Sie fehlen damit in jeder Feiertags- und '
'Vergleichstagsrechnung, ohne dass es auffaellt.';
